In [13]:
import numpy as np

In [2]:
Home_Location = (0, 0, 0)
x0_y0 = (254, 203.20) #X and Y in millimieters from (0,0,0) to the corner of the drop pad
solidoworks_measurement = 19.05 #distance from center to center of drop locations in millimeters

In [3]:
def get_xy(LLM_coordinate):
    x = x0_y0[0] + solidoworks_measurement * LLM_coordinate[0]
    y = x0_y0[1] + solidoworks_measurement * LLM_coordinate[1]
    drone_xy = (x,y)
    return drone_xy

In [6]:
test = get_xy((1,1))

In [7]:
print(test)

(273.05, 222.35000000000002)


In [10]:
Home_Location = (0, 0, 0)
x0_y0 = (254, 203.20)  # X and Y in millimeters from (0,0,0) to the corner of the drop pad
x1_y1 = (0.375, 0.375) # X and Y in millimeters from pad corner to center of first dropoff point 
solidoworks_measurement = 19.05  # distance from center to center of drop locations in millimeters

def get_xy(LLM_coordinate):
    x = x0_y0[0] + x1_y1[0] + solidoworks_measurement * LLM_coordinate[0]
    y = x0_y0[1] + x1_y1[1] + solidoworks_measurement * LLM_coordinate[1]
    drone_xy = (x, y)
    return drone_xy

# Create a 5x5 grid of drop-off positions
grid_size = 5
dropoff_positions = [[get_xy((i, j)) for j in range(grid_size)] for i in range(grid_size)]

# Print the drop-off positions
for row in dropoff_positions:
    print(row)

[(254.375, 203.675), (254.375, 222.72500000000002), (254.375, 241.775), (254.375, 260.82500000000005), (254.375, 279.875)]
[(273.425, 203.675), (273.425, 222.72500000000002), (273.425, 241.775), (273.425, 260.82500000000005), (273.425, 279.875)]
[(292.475, 203.675), (292.475, 222.72500000000002), (292.475, 241.775), (292.475, 260.82500000000005), (292.475, 279.875)]
[(311.525, 203.675), (311.525, 222.72500000000002), (311.525, 241.775), (311.525, 260.82500000000005), (311.525, 279.875)]
[(330.575, 203.675), (330.575, 222.72500000000002), (330.575, 241.775), (330.575, 260.82500000000005), (330.575, 279.875)]


In [12]:
print(dropoff_positions)

[[(254.375, 203.675), (254.375, 222.72500000000002), (254.375, 241.775), (254.375, 260.82500000000005), (254.375, 279.875)], [(273.425, 203.675), (273.425, 222.72500000000002), (273.425, 241.775), (273.425, 260.82500000000005), (273.425, 279.875)], [(292.475, 203.675), (292.475, 222.72500000000002), (292.475, 241.775), (292.475, 260.82500000000005), (292.475, 279.875)], [(311.525, 203.675), (311.525, 222.72500000000002), (311.525, 241.775), (311.525, 260.82500000000005), (311.525, 279.875)], [(330.575, 203.675), (330.575, 222.72500000000002), (330.575, 241.775), (330.575, 260.82500000000005), (330.575, 279.875)]]


In [16]:
import numpy as np

Home_Location = (0, 0, 0)
x0_y0 = (254, 203.30)  # X and Y in millimeters from (0,0,0) to the corner of the drop pad
solidoworks_measurement = 19.05  # distance from center to center of drop locations in millimeters

def get_xy(LLM_coordinate):
    x = x0_y0[0] + solidoworks_measurement * LLM_coordinate[0]
    y = x0_y0[1] + solidoworks_measurement * LLM_coordinate[1]
    # Convert to meters and truncate to 3 decimal points
    x = round(x / 1000, 6)
    y = round(y / 1000, 6)
    drone_xy = (x, y)
    return drone_xy

# Create a 5x5 grid of drop-off positions
grid_size = 5
dropoff_positions = [[get_xy((i, j)) for j in range(grid_size)] for i in range(grid_size)]

# Convert to numpy array
dropoff_positions_np = np.array(dropoff_positions)

# Set numpy print options
np.set_printoptions(precision=6, suppress=True, linewidth=100)

# Print the drop-off positions
print(dropoff_positions_np)

[[[0.254   0.2033 ]
  [0.254   0.22235]
  [0.254   0.2414 ]
  [0.254   0.26045]
  [0.254   0.2795 ]]

 [[0.27305 0.2033 ]
  [0.27305 0.22235]
  [0.27305 0.2414 ]
  [0.27305 0.26045]
  [0.27305 0.2795 ]]

 [[0.2921  0.2033 ]
  [0.2921  0.22235]
  [0.2921  0.2414 ]
  [0.2921  0.26045]
  [0.2921  0.2795 ]]

 [[0.31115 0.2033 ]
  [0.31115 0.22235]
  [0.31115 0.2414 ]
  [0.31115 0.26045]
  [0.31115 0.2795 ]]

 [[0.3302  0.2033 ]
  [0.3302  0.22235]
  [0.3302  0.2414 ]
  [0.3302  0.26045]
  [0.3302  0.2795 ]]]


In [17]:
import numpy as np

Home_Location = (0, 0, 0)
x0_y0 = (254, 203.30)  # X and Y in millimeters from (0,0,0) to the corner of the drop pad
solidoworks_measurement = 19.05  # distance from center to center of drop locations in millimeters

def get_xy(LLM_coordinate):
    x = x0_y0[0] + solidoworks_measurement * LLM_coordinate[0]
    y = x0_y0[1] + solidoworks_measurement * LLM_coordinate[1]
    # Convert to meters and truncate to 3 decimal points
    x = round(x / 1000, 3)
    y = round(y / 1000, 3)
    drone_xy = (x, y)
    return drone_xy

# Create a 5x5 grid of drop-off positions
grid_size = 5
dropoff_positions = np.array([[get_xy((i, j)) for j in range(grid_size)] for i in range(grid_size)])

# Set numpy print options
np.set_printoptions(precision=3, suppress=True, linewidth=200)

# Print the drop-off positions
print(dropoff_positions)

[[[0.254 0.203]
  [0.254 0.222]
  [0.254 0.241]
  [0.254 0.26 ]
  [0.254 0.28 ]]

 [[0.273 0.203]
  [0.273 0.222]
  [0.273 0.241]
  [0.273 0.26 ]
  [0.273 0.28 ]]

 [[0.292 0.203]
  [0.292 0.222]
  [0.292 0.241]
  [0.292 0.26 ]
  [0.292 0.28 ]]

 [[0.311 0.203]
  [0.311 0.222]
  [0.311 0.241]
  [0.311 0.26 ]
  [0.311 0.28 ]]

 [[0.33  0.203]
  [0.33  0.222]
  [0.33  0.241]
  [0.33  0.26 ]
  [0.33  0.28 ]]]


In [19]:
import numpy as np

Home_Location = (0, 0, 0)
x0_y0 = (254, 203.20)  # X and Y in millimeters from (0,0,0) to the corner of the drop pad
solidoworks_measurement = 19.05  # distance from center to center of drop locations in millimeters

def get_xy(LLM_coordinate):
    x = x0_y0[0] + solidoworks_measurement * LLM_coordinate[0]
    y = x0_y0[1] + solidoworks_measurement * LLM_coordinate[1]
    # Convert to meters and truncate to 6 decimal points
    x = round(x / 1000, 6)
    y = round(y / 1000, 6)
    drone_xy = (x, y)
    return drone_xy

# Create a 5x5 grid of drop-off positions
grid_size = 5
dropoff_positions = np.array([[get_xy((i, j)) for j in range(grid_size)] for i in range(grid_size)])

# Set numpy print options
np.set_printoptions(precision=6, suppress=True, linewidth=500)

# Print the drop-off positions
print(dropoff_positions)

[[[0.254   0.2032 ]
  [0.254   0.22225]
  [0.254   0.2413 ]
  [0.254   0.26035]
  [0.254   0.2794 ]]

 [[0.27305 0.2032 ]
  [0.27305 0.22225]
  [0.27305 0.2413 ]
  [0.27305 0.26035]
  [0.27305 0.2794 ]]

 [[0.2921  0.2032 ]
  [0.2921  0.22225]
  [0.2921  0.2413 ]
  [0.2921  0.26035]
  [0.2921  0.2794 ]]

 [[0.31115 0.2032 ]
  [0.31115 0.22225]
  [0.31115 0.2413 ]
  [0.31115 0.26035]
  [0.31115 0.2794 ]]

 [[0.3302  0.2032 ]
  [0.3302  0.22225]
  [0.3302  0.2413 ]
  [0.3302  0.26035]
  [0.3302  0.2794 ]]]


In [20]:
print(dropoff_positions[0])

[[0.254   0.2032 ]
 [0.254   0.22225]
 [0.254   0.2413 ]
 [0.254   0.26035]
 [0.254   0.2794 ]]


In [26]:
import numpy as np

Home_Location = (0, 0, 0)
x0_y0 = (254, 203.20)  # X and Y in millimeters from (0,0,0) to the corner of the drop pad
x1_y1 = (0.375, 0.375) # X and Y in millimeters from pad corner to center of first dropoff point 
solidoworks_measurement = 19.05  # distance from center to center of drop locations in millimeters

def get_xy(LLM_coordinate):
    x = x0_y0[0] + x1_y1[0] + solidoworks_measurement * LLM_coordinate[0]
    y = x0_y0[1] + x1_y1[1] + solidoworks_measurement * LLM_coordinate[1]
    x = round(x / 1000, 6)
    y = round(y / 1000, 6)
    drone_xy = (x, y)
    return drone_xy

# Create a 5x5 grid of drop-off positions
grid_size = 5
dropoff_positions = [[get_xy((i, j)) for j in range(grid_size)] for i in range(grid_size)]

# Convert to numpy array for easy printing
dropoff_positions_np = np.array(dropoff_positions)

# Print the drop-off positions in a formatted way
for row in dropoff_positions_np:
    print(' '.join([f"({x:.3f}, {y:.3f})" for x, y in row]))

(0.254, 0.204) (0.254, 0.223) (0.254, 0.242) (0.254, 0.261) (0.254, 0.280)
(0.273, 0.204) (0.273, 0.223) (0.273, 0.242) (0.273, 0.261) (0.273, 0.280)
(0.292, 0.204) (0.292, 0.223) (0.292, 0.242) (0.292, 0.261) (0.292, 0.280)
(0.312, 0.204) (0.312, 0.223) (0.312, 0.242) (0.312, 0.261) (0.312, 0.280)
(0.331, 0.204) (0.331, 0.223) (0.331, 0.242) (0.331, 0.261) (0.331, 0.280)


In [27]:
print(dropoff_positions_np)

[[[0.254375 0.203575]
  [0.254375 0.222625]
  [0.254375 0.241675]
  [0.254375 0.260725]
  [0.254375 0.279775]]

 [[0.273425 0.203575]
  [0.273425 0.222625]
  [0.273425 0.241675]
  [0.273425 0.260725]
  [0.273425 0.279775]]

 [[0.292475 0.203575]
  [0.292475 0.222625]
  [0.292475 0.241675]
  [0.292475 0.260725]
  [0.292475 0.279775]]

 [[0.311525 0.203575]
  [0.311525 0.222625]
  [0.311525 0.241675]
  [0.311525 0.260725]
  [0.311525 0.279775]]

 [[0.330575 0.203575]
  [0.330575 0.222625]
  [0.330575 0.241675]
  [0.330575 0.260725]
  [0.330575 0.279775]]]


In [29]:
print(dropoff_positions[0][0])

(0.254375, 0.203575)


In [30]:
E_spot1 = get_xy((0,0))
print(E_spot1)

(0.254375, 0.203575)
